import * as T from 'three';
import {OrbitControls} from './第三方依赖/OrbitControls.js';
const $=s=>document.querySelector(s),reduced=matchMedia('(prefers-reduced-motion: reduce)');
const data=[[
 ['哑光外层','表面以细腻的哑光质感呈现。切换左侧配色，或转动模型，观察光线沿弧面移动。'],['连续包边','边框沿机身轮廓延伸，四角用连续圆弧过渡。翻到正面，可以看到包覆屏幕周围的边缘。'],['镜头开口','开口与镜头区对应，外侧围边形成高差。点选“细节”，转到局部视角观察。']],
 [['外层背板','背板决定外观与触感。这份概念模型将它独立拆出，便于看清开口、外表面和内部层次。'],['内侧衬层','衬层位于手机与外壳之间。这里用浅色区分贴合面，展示结构关系；不是实测材料性能。'],['环形组件','环形组件示意磁吸区域的位置。它与外壳、手机分层展示，不代表已验证充电或配件兼容性。']],
 [['镜头围边','围边高于镜片表面。转到侧面，观察高差如何让镜片避开接触平面。'],['包覆边缘','边框围绕设备边缘形成包覆，圆角与壳体连贯过渡。这里只展示几何设计，不演示未经验证的跌落性能。'],['侧边按键','按键覆盖区从边框上轻微凸起，便于从侧面辨认位置。转到侧面，可看到它与机身的位置关系。']]
];
const short=[['表面','包边','开口'],['背板','衬层','环形组件'],['镜头','边缘','按键']];
let mode=0,selected=0,feature=0,amount=0,amountNow=0,rotating=false,flipped=false,visible=true,frame=0,renderer,controls,scene,camera,assembly,back,liner,ring,frameMesh,cameraRim,buttonMesh,phone,viewTween=false;
const targetView=new T.Vector3(5,3,10),colors=['#78877d','#b66b50','#74899c','#3d4140'],names=['苔灰','陶土','雾蓝','石墨'];
const shellMat=new T.MeshStandardMaterial({color:colors[0],roughness:.72,metalness:.04}),edgeMat=shellMat.clone(),linerMat=new T.MeshStandardMaterial({color:'#e2dfce',roughness:.95}),silver=new T.MeshStandardMaterial({color:'#abb2ae',roughness:.28,metalness:.8}),dark=new T.MeshStandardMaterial({color:'#333a38',roughness:.5}),glass=new T.MeshStandardMaterial({color:'#183337',roughness:.12,metalness:.7});
function rounded(w,h,r,cx=0,cy=0){const s=new T.Shape(),x=cx-w/2,y=cy-h/2;s.moveTo(x+r,y);s.lineTo(x+w-r,y);s.quadraticCurveTo(x+w,y,x+w,y+r);s.lineTo(x+w,y+h-r);s.quadraticCurveTo(x+w,y+h,x+w-r,y+h);s.lineTo(x+r,y+h);s.quadraticCurveTo(x,y+h,x,y+h-r);s.lineTo(x,y+r);s.quadraticCurveTo(x,y,x+r,y);return s;}
function meshShape(shape,depth,mat){const g=new T.ExtrudeGeometry(shape,{depth,bevelEnabled:true,bevelSegments:3,bevelSize:.025,bevelThickness:.025,steps:1,curveSegments:18});g.translate(0,0,-depth/2);const m=new T.Mesh(g,mat);m.castShadow=true;m.receiveShadow=true;return m}
function slab(w,h,r,d,mat){return meshShape(rounded(w,h,r),d,mat)}
function holeShape(w,h,r,hole){const s=rounded(w,h,r);s.holes.push(new T.Path(hole.getPoints(36)));return s}
function setAmount(v){amount=v;$('#separation').value=Math.round(v*100);$('#amount').value=Math.round(v*100)+'%';if(reduced.matches)amountNow=amount;wake()}
function select(i,focus=false){selected=i;$('#info-number').textContent=`0${i+1} / 03`;$('#info-title').textContent=data[mode][i][0];$('#info-text').textContent=data[mode][i][1];document.querySelectorAll('[data-choice]').forEach(b=>b.setAttribute('aria-pressed',String(+b.dataset.choice===i)));document.querySelectorAll('.mini-diagram path').forEach((p,j)=>{p.style.stroke=j===i?'#955537':'#929c89';p.style.transform=`translateY(${mode===1?(j-1)*8:0}px)`});const b=$('.info-body');b.classList.remove('change');void b.offsetWidth;b.classList.add('change');if(focus&&mode===2&&camera){const positions=[[0,3.3,7],[5,-2,8],[11,1,5]];targetView.set(...positions[i]);viewTween=true;}wake()}
function setMode(i){mode=i;document.querySelectorAll('[data-mode]').forEach(b=>b.setAttribute('aria-pressed',String(+b.dataset.mode===i)));$('#choices').innerHTML=short[i].map((n,j)=>`<button data-choice="${j}" aria-pressed="${j===0}"><span>0${j+1}</span>${n}</button>`).join('');$('#hotspots').innerHTML=short[i].map((n,j)=>`<button class="hotspot" data-choice="${j}" aria-label="${n}：查看说明" aria-pressed="${j===0}">0${j+1}</button>`).join('');document.querySelectorAll('[data-choice]').forEach(b=>b.onclick=()=>select(+b.dataset.choice,true));$('#scene-caption').textContent=['拖动检视背面与侧边 · 双指缩放','拖动滑杆，逐层拉开结构','点选编号，切换到对应的观察视角'][i];setAmount(i===1?.95:0);if(camera){targetView.set(...(i===1?[10,3,10]:[5,3,10]));viewTween=true;}select(0);}
document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>setMode(+b.dataset.mode));$('#start').onclick=()=>{setMode(1);$('.stage').scrollIntoView({behavior:reduced.matches?'instant':'smooth',block:'center'})};$('#separation').oninput=e=>{if(mode!==1)setMode(1);setAmount(+e.target.value/100)};
document.querySelectorAll('[data-color]').forEach(b=>b.onclick=()=>{const i=+b.dataset.color;shellMat.color.set(colors[i]);edgeMat.color.set(colors[i]);$('#color-name').textContent=names[i];document.querySelectorAll('[data-color]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));wake()});
$('#motion').onclick=()=>{rotating=!rotating;$('#motion').textContent=rotating?'暂停旋转':'自动旋转';$('#motion').setAttribute('aria-pressed',String(rotating));wake()};reduced.addEventListener('change',()=>{rotating=false;$('#motion').textContent='自动旋转';$('#motion').setAttribute('aria-pressed','false');wake()});
const detailTitles=['让镜片避开平面。','沿轮廓，包住边缘。','让手指找到位置。'];
function selectFeature(i){feature=i;document.querySelectorAll('[data-feature]').forEach(b=>b.setAttribute('aria-pressed',String(+b.dataset.feature===i)));$('#detail-label').textContent=`0${i+1} / ${data[2][i][0]}`;$('#detail-heading').textContent=detailTitles[i];$('#detail-copy').textContent=data[2][i][1];const p=$('.paper-right');p.classList.remove('turn');void p.offsetWidth;p.classList.add('turn');}
document.querySelectorAll('[data-feature]').forEach(b=>b.onclick=()=>selectFeature(+b.dataset.feature));$('#inspect').onclick=()=>{setMode(2);select(feature,true);$('.stage').scrollIntoView({behavior:reduced.matches?'instant':'smooth',block:'center'})};
try{
scene=new T.Scene();camera=new T.PerspectiveCamera(35,1,.1,100);camera.position.copy(targetView);renderer=new T.WebGLRenderer({canvas:$('#scene'),alpha:true,antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;
scene.add(new T.HemisphereLight('#fff9ec','#6c796c',2));const key=new T.DirectionalLight('#fffbef',3);key.position.set(-4,8,6);key.castShadow=true;key.shadow.mapSize.set(2048,2048);Object.assign(key.shadow.camera,{left:-8,right:8,top:8,bottom:-8});key.shadow.normalBias=.04;scene.add(key);const fill=new T.DirectionalLight('#dce8ee',1.5);fill.position.set(5,2,-4);scene.add(fill);
controls=new OrbitControls(camera,renderer.domElement);controls.target.set(0,0,.3);controls.enablePan=false;controls.minDistance=7;controls.maxDistance=19;controls.update();controls.addEventListener('start',()=>{viewTween=false});controls.addEventListener('change',()=>render());
assembly=new T.Group();assembly.rotation.z=-.13;scene.add(assembly);
phone=slab(2.55,5.35,.36,.27,silver);phone.position.z=-.14;assembly.add(phone);const screen=slab(2.42,5.2,.31,.012,dark);screen.position.z=-.3;assembly.add(screen);
const cameraIsland=slab(1.25,1.32,.24,.17,silver);cameraIsland.position.set(-.52,1.74,.06);assembly.add(cameraIsland);
for(const [x,y] of [[-.8,2.06],[-.25,1.76],[-.8,1.43]]){const lens=new T.Mesh(new T.CylinderGeometry(.24,.24,.12,48),dark);lens.rotation.x=Math.PI/2;lens.position.set(x,y,.21);assembly.add(lens);const face=new T.Mesh(new T.CircleGeometry(.19,48),glass);face.position.set(x,y,.276);assembly.add(face);const glint=new T.Mesh(new T.CircleGeometry(.052,24),new T.MeshBasicMaterial({color:'#8eafaa'}));glint.position.set(x-.04,y+.055,.279);assembly.add(glint)}
const opening=rounded(1.43,1.56,.25,-.52,1.74);
back=meshShape(holeShape(2.75,5.58,.43,opening),.08,shellMat);back.position.z=.36;assembly.add(back);
liner=meshShape(holeShape(2.62,5.46,.38,opening),.04,linerMat);liner.position.z=.21;assembly.add(liner);
const edge=holeShape(2.83,5.67,.46,rounded(2.55,5.36,.36));frameMesh=meshShape(edge,.52,edgeMat);frameMesh.position.z=.035;assembly.add(frameMesh);
const rimShape=rounded(1.59,1.72,.3,-.52,1.74);rimShape.holes.push(new T.Path(opening.getPoints(36)));cameraRim=meshShape(rimShape,.15,edgeMat);cameraRim.position.z=.46;back.add(cameraRim);cameraRim.position.z=.10;
ring=new T.Group();const ringMesh=new T.Mesh(new T.TorusGeometry(.8,.055,12,80),silver);ring.add(ringMesh);const stem=slab(.11,.33,.045,.028,silver);stem.position.set(0,-1.04,0);ring.add(stem);ring.position.set(0,-.35,.29);assembly.add(ring);
// A subtle exterior registration ring, separate from the internal component.
const outline=new T.Mesh(new T.TorusGeometry(.8,.012,8,80),new T.MeshStandardMaterial({color:'#b1bcb2',roughness:.8}));outline.position.set(0,-.35,.085);back.add(outline);const outerStem=slab(.027,.28,.009,.007,outline.material);outerStem.position.set(0,-1.38,.085);back.add(outerStem);
buttonMesh=slab(.10,.7,.045,.16,edgeMat);buttonMesh.position.set(1.45,.65,.02);assembly.add(buttonMesh);const b2=slab(.09,.52,.04,.13,edgeMat);b2.position.set(-1.44,.85,0);assembly.add(b2);
// Engraved name, generated locally as a texture rather than a fake product photograph.
const label=document.createElement('canvas');label.width=512;label.height=128;const ctx=label.getContext('2d');ctx.fillStyle='#dce3d9';ctx.font='32px serif';ctx.textAlign='center';ctx.fillText('A R C',256,70);const tex=new T.CanvasTexture(label);tex.colorSpace=T.SRGBColorSpace;const word=new T.Mesh(new T.PlaneGeometry(.75,.19),new T.MeshBasicMaterial({map:tex,transparent:true,depthWrite:false}));word.position.set(0,-2.15,.085);back.add(word);
const floor=new T.Mesh(new T.PlaneGeometry(40,40),new T.ShadowMaterial({opacity:.11}));floor.rotation.x=-Math.PI/2;floor.position.y=-3.1;scene.add(floor);floor.receiveShadow=true;
const resize=()=>{const r=$('#viewport').getBoundingClientRect();renderer.setSize(r.width,r.height,false);camera.aspect=r.width/r.height;camera.updateProjectionMatrix();wake()};new ResizeObserver(resize).observe($('#viewport'));resize();$('#loading').hidden=true;
$('#front').onclick=()=>{flipped=!flipped;targetView.set(flipped?-4:5,2,flipped?-11:10);viewTween=true;$('#front').textContent=flipped?'翻到背面 ↺':'翻到正面 ↺';wake()};$('#reset').onclick=()=>{assembly.rotation.set(0,0,-.13);targetView.set(...(mode===1?[10,3,10]:[5,3,10]));flipped=false;viewTween=true;$('#front').textContent='翻到正面 ↺';wake()};$('#rotate').onclick=()=>{assembly.rotation.y+=Math.PI/6;wake()};$('#scene').onkeydown=e=>{if(['ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();assembly.rotation.y+=(e.key==='ArrowLeft'?-1:1)*Math.PI/12;wake()}};
const ray=new T.Raycaster();let start;$('#scene').addEventListener('pointerdown',e=>start=[e.clientX,e.clientY]);$('#scene').addEventListener('pointerup',e=>{if(!start||Math.hypot(e.clientX-start[0],e.clientY-start[1])>6)return;const r=$('#scene').getBoundingClientRect();ray.setFromCamera(new T.Vector2((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1),camera);const hit=ray.intersectObject(assembly,true)[0];if(!hit)return;let o=hit.object;if(o===cameraRim){setMode(2);select(0,true)}else if(o===buttonMesh){setMode(2);select(2,true)}else if(mode===1){select(o===liner?1:(o===ringMesh||o===stem)?2:0)}else select(o===frameMesh?1:0)});
new IntersectionObserver(e=>{visible=e[0].isIntersecting;if(visible)wake()}).observe($('#viewport'));document.addEventListener('visibilitychange',()=>{if(!document.hidden)wake()});$('#scene').addEventListener('webglcontextlost',e=>{e.preventDefault();$('#fallback').hidden=false;$('#scene').hidden=true;$('#hotspots').hidden=true;cancelAnimationFrame(frame)});
}catch(e){console.error(e);$('#loading').hidden=true;$('#fallback').hidden=false;$('#scene').hidden=true;document.querySelectorAll('.scene-controls button,#separation,#motion').forEach(b=>b.disabled=true)}
function anchors(){return mode===1?[back,liner,ring]:mode===2?[cameraRim,frameMesh,buttonMesh]:[back,frameMesh,cameraRim]}
function render(){if(!renderer||!assembly)return;back.position.z=.36+amountNow*3.0;liner.position.z=.21+amountNow*.9;ring.position.z=.29+amountNow*1.8;renderer.render(scene,camera);const r=$('#viewport').getBoundingClientRect();assembly.updateMatrixWorld(true);anchors().forEach((o,i)=>{const v=new T.Vector3();if(o===frameMesh)v.set(1.3,-2.5,0);else if(o===cameraRim)v.set(-.52,1.74,.12);else if(o===back)v.set(.6,-1.4,.08);o.localToWorld(v);v.project(camera);const x=(v.x*.5+.5)*r.width,y=(-v.y*.5+.5)*r.height;const hx=Math.max(25,Math.min(r.width-25,x+[-60,65,55][i])),hy=Math.max(25,Math.min(r.height-45,y+[-30,25,-35][i]));const el=document.querySelectorAll('.hotspot')[i];if(!el)return;el.style.left=hx+'px';el.style.top=hy+'px';el.hidden=v.z>1||v.z< -1;document.querySelectorAll('#leaders path')[i].setAttribute('d',`M ${hx} ${hy} L ${x} ${y}`);});}
function wake(){if(!renderer||frame)return;frame=requestAnimationFrame(tick)}
let last=0;
function tick(t){frame=0;if(!visible||document.hidden)return;const dt=Math.min((t-last)/1000,.04);last=t;const k=reduced.matches?1:.09;amountNow+=(amount-amountNow)*k;if(viewTween){camera.position.lerp(targetView,k);controls.update();if(camera.position.distanceTo(targetView)<.012)viewTween=false}if(rotating&&!reduced.matches)assembly.rotation.y+=dt*.25;render();if(viewTween||Math.abs(amount-amountNow)>.001||(rotating&&!reduced.matches))wake()}
setMode(0);
window.addEventListener('pagehide',()=>{cancelAnimationFrame(frame);controls?.dispose();scene?.traverse(o=>{o.geometry?.dispose();if(o.material)for(const m of [].concat(o.material)){m.map?.dispose();m.dispose()}});renderer?.dispose()});
