import * as T from 'three';
import {OrbitControls} from './第三方依赖/OrbitControls.js';
const canvas=document.querySelector('#scene'),loading=document.querySelector('#loading'),motion=document.querySelector('#motion'),reduce=matchMedia('(prefers-reduced-motion: reduce)');
let moving=!reduce.matches,controls,renderer;
function updateMotion(){motion.setAttribute('aria-pressed',String(moving));motion.textContent=moving?'暂停漂浮 Ⅱ':'开启漂浮 ↻';}updateMotion();
const scene=new T.Scene(),cam=new T.PerspectiveCamera(35,1,.1,50);cam.position.set(0,1.1,9.5);
const composition=new T.Group();scene.add(composition);const objects={};
function material(color,roughness=.7,metalness=0){return new T.MeshStandardMaterial({color,roughness,metalness});}
const ink=material('#303a32'),sage=material('#858a6e'),cream=material('#dad5bd'),paper=material('#efeadb'),silver=material('#b4b3a6',.36,.55),black=material('#232b28',.65,.1),lens=material('#344849',.12,.5);
function box(w,h,d,r,mat){const s=new T.Shape(),x=-w/2,y=-h/2;s.moveTo(x+r,y);s.lineTo(x+w-r,y);s.quadraticCurveTo(x+w,y,x+w,y+r);s.lineTo(x+w,y+h-r);s.quadraticCurveTo(x+w,y+h,x+w-r,y+h);s.lineTo(x+r,y+h);s.quadraticCurveTo(x,y+h,x,y+h-r);s.lineTo(x,y+r);s.quadraticCurveTo(x,y,x+r,y);const geo=new T.ExtrudeGeometry(s,{depth:d,bevelEnabled:true,bevelSegments:3,steps:1,bevelSize:.025,bevelThickness:.025,curveSegments:12});geo.translate(0,0,-d/2);const m=new T.Mesh(geo,mat);m.castShadow=true;m.receiveShadow=true;return m;}
function cyl(radius,depth,mat){const m=new T.Mesh(new T.CylinderGeometry(radius,radius,depth,64),mat);m.rotation.x=Math.PI/2;m.castShadow=true;return m;}
function labelTexture(type){const c=document.createElement('canvas');c.width=768;c.height=1024;const g=c.getContext('2d');g.fillStyle=type==='book'?'#747d60':'#e7e1d1';g.fillRect(0,0,768,1024);g.fillStyle=type==='book'?'#ede8d6':'#424c3b';g.font='22px sans-serif';g.fillText(type==='book'?'CHARLIE / FIELD NOTES':'CHARLIE / WEB STUDIES',65,95);g.fillRect(65,125,638,2);g.font='94px Georgia';g.fillText(type==='book'?'Ways of':'Ideas,',60,260);g.font='italic 94px Georgia';g.fillText(type==='book'?'seeing.':'in progress.',60,363);if(type==='book'){g.strokeStyle='#d4d5bd';g.lineWidth=2;for(let i=0;i<7;i++){g.beginPath();g.ellipse(382,650,105+i*25,140+i*13,-.28,0,Math.PI*2);g.stroke();}}else{g.fillStyle='#b1b497';g.fillRect(65,432,638,370);g.strokeStyle='#55644c';g.lineWidth=3;g.beginPath();g.moveTo(120,725);g.bezierCurveTo(260,380,360,900,650,485);g.stroke();g.fillStyle='#975437';g.beginPath();g.arc(525,565,62,0,Math.PI*2);g.fill();}g.fillStyle=type==='book'?'#e8e4d3':'#535d47';g.font='19px sans-serif';g.fillText('OBSERVE. ARRANGE. MAKE.',65,930);const t=new T.CanvasTexture(c);t.colorSpace=T.SRGBColorSpace;return t;}
function face(w,h,texture){return new T.Mesh(new T.PlaneGeometry(w,h),new T.MeshStandardMaterial({map:texture,roughness:.9}));}
const book=new T.Group();book.add(box(1.55,2.15,.23,.025,paper));for(const z of [-.16,.16]){const cover=box(1.63,2.23,.035,.025,sage);cover.position.z=z;book.add(cover);}const cover=face(1.6,2.2,labelTexture('book'));cover.position.z=.205;book.add(cover);const spine=box(.07,2.2,.32,.02,sage);spine.position.x=-.78;book.add(spine);for(let i=0;i<8;i++){const page=new T.Mesh(new T.BoxGeometry(1.48,.005,.002),cream);page.position.set(0,-1.078,-.1+i*.028);book.add(page);}book.position.set(-1.35,.8,-.15);book.rotation.set(-.13,.24,-.2);composition.add(book);objects.book=book;
const camera=new T.Group();camera.add(box(2.15,1.27,.65,.15,ink));const top=box(2.13,.23,.66,.08,silver);top.position.y=.5;camera.add(top);const bottom=box(2.09,.12,.66,.06,silver);bottom.position.y=-.56;camera.add(bottom);
for(const [r,d,z,mat] of [[.56,.13,.36,silver],[.5,.35,.57,black],[.43,.09,.78,silver],[.38,.1,.86,black],[.31,.016,.921,lens]]){const m=cyl(r,d,mat);m.position.set(-.18,-.02,z);camera.add(m);}
for(let i=0;i<40;i++){const a=i/40*Math.PI*2;const ridge=new T.Mesh(new T.BoxGeometry(.018,.045,.23),silver);ridge.position.set(-.18+Math.cos(a)*.497,-.02+Math.sin(a)*.497,.59);ridge.rotation.z=a;camera.add(ridge);}
const finder=box(.38,.22,.03,.025,black);finder.position.set(.68,.3,.35);camera.add(finder);const flash=box(.43,.16,.03,.015,paper);flash.position.set(-.67,.43,.355);camera.add(flash);const shutter=cyl(.14,.08,black);shutter.rotation.x=0;shutter.position.set(.73,.68,0);camera.add(shutter);const dial=cyl(.24,.09,silver);dial.rotation.x=0;dial.position.set(-.65,.68,0);camera.add(dial);const dot=new T.Mesh(new T.SphereGeometry(.038,16,16),material('#a25d41'));dot.position.set(.6,-.16,.355);camera.add(dot);camera.position.set(.77,-.4,.7);camera.rotation.set(-.06,-.3,.15);composition.add(camera);objects.camera=camera;
const card=new T.Group();card.add(box(1.65,2.16,.045,.025,paper));const cf=face(1.61,2.12,labelTexture('card'));cf.position.z=.055;card.add(cf);card.position.set(1.38,1.2,-.85);card.rotation.set(-.1,-.25,.23);composition.add(card);objects.card=card;
const ring=new T.Mesh(new T.TorusGeometry(2.9,.006,5,140),material('#b9beaa'));ring.rotation.set(.65,.15,-.3);ring.position.z=-1.5;scene.add(ring);
const floor=new T.Mesh(new T.PlaneGeometry(200,200),new T.ShadowMaterial({color:'#586045',opacity:.12}));floor.rotation.x=-Math.PI/2;floor.position.y=-2;floor.receiveShadow=true;scene.add(floor);scene.add(new T.HemisphereLight('#fffcf2','#818a6d',2.6));const light=new T.DirectionalLight('#fff6dd',3.8);light.position.set(-3,7,6);light.castShadow=true;light.shadow.mapSize.set(1024,1024);light.shadow.camera.left=-6;light.shadow.camera.right=6;light.shadow.camera.top=6;light.shadow.camera.bottom=-6;light.shadow.normalBias=.025;scene.add(light);const fill=new T.DirectionalLight('#e9efff',1.3);fill.position.set(5,1,-2);scene.add(fill);
let selection='all',phase=0,last=0;const poses=Object.fromEntries(Object.entries(objects).map(([key,obj])=>[key,{pos:obj.position.clone(),rot:obj.rotation.clone()}]));
try{renderer=new T.WebGLRenderer({canvas,alpha:true,antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.05;renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;controls=new OrbitControls(cam,canvas);canvas.style.touchAction='pan-y';controls.enableZoom=false;controls.enablePan=false;controls.enableDamping=true;controls.minPolarAngle=.65;controls.maxPolarAngle=2;controls.rotateSpeed=.6;controls.target.set(0,.2,0);new ResizeObserver(()=>{const rect=canvas.getBoundingClientRect();renderer.setSize(rect.width,rect.height,false);cam.aspect=rect.width/rect.height;cam.updateProjectionMatrix();}).observe(canvas);loading.hidden=true;document.body.dataset.scene='ready';
function frame(t){requestAnimationFrame(frame);if(document.hidden){last=t;return;}const dt=Math.min((t-last)/1000,.04);last=t;if(moving)phase+=dt;const amount=reduce.matches?1:1-Math.exp(-dt*6);Object.entries(objects).forEach(([key,obj],i)=>{const base=poses[key];const selected=selection===key;const dest=selection==='all'?base.pos.clone():new T.Vector3(selected?0:base.pos.x*2.5,selected?.35:base.pos.y,selected?.7:-1.8);if(moving)dest.y+=Math.sin(phase*.8+i*2)*.08;obj.position.lerp(dest,amount);const targetScale=selection==='all'?1:selected?1.25:.001;obj.scale.lerp(new T.Vector3(targetScale,targetScale,targetScale),amount);obj.rotation.x=base.rot.x+(moving?Math.sin(phase*.5+i)*.035:0);obj.rotation.y=base.rot.y+(moving?Math.sin(phase*.35+i)*.09:0);});controls.update();renderer.render(scene,cam);}requestAnimationFrame(frame);
}catch(e){console.error(e);loading.textContent='三维场景暂不可用，仍可浏览下方作品。';document.body.dataset.scene='error';}
motion.onclick=()=>{moving=!moving;updateMotion();};reduce.addEventListener('change',()=>{if(reduce.matches){moving=false;updateMotion();}});
function reset(){cam.position.set(0,1.1,9.5);controls?.target.set(0,.2,0);controls?.update();}document.querySelector('#reset').onclick=()=>{choose('all');reset();};
const captions={all:['01 / OBJECTS','想法的随身物件。','一本书，一台相机，<br>还有正在成形的页面。'],book:['01 / FIELD NOTES','先把想法收集起来。','书页、笔记与留白。<br>给零散的想法一个位置。'],camera:['02 / OBSERVATION','换个角度看。','取景、光线与距离。<br>把注意力放回细节。'],card:['03 / MAKING','让想法成为页面。','次序、比例与交互。<br>在具体的作品中继续调整。']};
function choose(key){selection=key;const c=captions[key];document.querySelector('#object-num').textContent=c[0];document.querySelector('#object-name').textContent=c[1];document.querySelector('#object-copy').innerHTML=c[2];document.querySelectorAll('[data-object]').forEach(b=>{const active=b.dataset.object===key;b.classList.toggle('active',active);b.setAttribute('aria-pressed',String(active));});reset();document.body.dataset.object=key;}
document.querySelectorAll('[data-object]').forEach(b=>b.onclick=()=>choose(b.dataset.object));canvas.addEventListener('keydown',e=>{if(!['ArrowLeft','ArrowRight'].includes(e.key))return;e.preventDefault();const s=new T.Spherical().setFromVector3(cam.position);s.theta+=e.key==='ArrowLeft'?-.15:.15;cam.position.setFromSpherical(s);});
const dialog=document.querySelector('#brief-dialog');document.querySelector('#brief').onclick=()=>dialog.showModal();document.querySelector('#download').onclick=()=>{const idea=document.querySelector('#project-idea').value.trim(),audience=document.querySelector('#project-audience').value.trim();if(!idea){document.querySelector('#brief-status').textContent='先写下一点项目想法。';document.querySelector('#project-idea').focus();return;}const blob=new Blob(['项目想法\n'+idea+'\n\n希望谁看到\n'+(audience||'待补充')+'\n'],{type:'text/plain;charset=utf-8'});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='项目便签.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);document.querySelector('#brief-status').textContent='便签已下载，尚未发送给任何人。';};
