import * as T from 'three';
import {OrbitControls} from './第三方依赖/OrbitControls.js';
const $=s=>document.querySelector(s),reduce=matchMedia('(prefers-reduced-motion: reduce)');
const chapters=[
 {title:'观察',en:'OBSERVATION',lead:'你经常从一个具体的画面开始：片名的笔触、物件周围的解析、文字之间的空白。',quote:'“我最想保留的是适当的留空以及零碎但不散乱的文字排布。”',notes:[['画面里的秩序','你喜欢简约陈列，也在意信息之间的关系。空白不是剩余空间，而是阅读的一部分。'],['从作品进入','《蓦然回首》、电影专题与物件展台，都是你探索审美的具体入口。'],['说出具体差别','你会指出标题太重、文案太煽情，或图片裁切没有呈现真正喜欢的部分。']],thought:'你的审美判断往往在看到样本之后变得更准确。与其先定义一个风格名，你更愿意通过比较找到它。'},
 {title:'制作',en:'MAKING',lead:'你希望想法尽早变成可以看见、触碰和比较的东西，再用反馈推动下一版。',quote:'“我想通过慢慢看到成果的方式一点点进入我想要表达的主题。”',notes:[['内容与视觉','你明确选择过“内容策划 + AI 视觉制作”的展示方向。内容结构和画面生成需要一起考虑。'],['从平面到空间','服装、门锁、发动机与水晶球的练习，让观察延伸到旋转、拆解和状态变化。'],['连续的视觉资料','《时之瓶》的角色、场景和路线资料，让单张图逐步进入更完整的创作流程。']],thought:'你使用 AI 不只是为了得到一张成图，也在练习把想法拆成可以制作、检查和继续修改的步骤。'},
 {title:'整理',en:'ORGANIZATION',lead:'作品变多之后，你开始关心它们如何归档、交接，以及下一次能不能顺利接着做。',quote:'“把小的项目归入大的项目分组里面……用中文来命名。”',notes:[['找得到','你要求按项目分组，用中文命名，让文件的位置和用途能够一眼看清。'],['接得上','进度、参考与交接资料同样重要。任务换到新的对话，也应该保留上下文。'],['留下方法','从偏好记录、正反案例到验收标准，你希望学习结果能够沉淀成可复用的 Skill。']],thought:'在你的工作里，整理并不是创作结束后的附加步骤。它决定一个尝试能否积累成下一次的起点。'},
 {title:'偏好',en:'PREFERENCES',lead:'有些偏好已经清楚，有些仍然留着空位。它们来自具体作品，不必一次写成固定答案。',quote:'“最喜欢周围的手稿零件解析，最想改掉标题（不要描述性叙述）。”',notes:[['保留','有用途的手稿解析、适当留白、清晰的文字层级，以及能看见物件细节的呈现。'],['调整','过大过黑的字体、过度解释和煽情文案，以及失去重点的图片展示。'],['继续试','更丰富的动效、书页展开和可检视的三维物件。复杂交互也要保留阅读的秩序。']],thought:'你要形成的个人风格，可能不只是一组颜色和字体，更是一套选择：哪些值得突出，哪些可以删去。'}
];
let bookModel,sceneCards=[],hotspotTargets=[],detailIndex=0,sceneReady=false,arranged=false,buildStep=0,tasteValue=.65,pendingChapter=null;
let current=0,turning=false,moving=!reduce.matches,openTarget=.90,openNow=.90,explodeTarget=0,explodeNow=0,renderer,controls,scene,camera,world,hinge,turnPage,cameraModel,pen,parts=[],raf=0,visible=true;
function updateContent(i){const c=chapters[i];$('#chapter-title').textContent=c.title;$('#chapter-en').textContent=c.en;$('#chapter-no').textContent=`CHAPTER 0${i+1}`;$('#chapter-lead').textContent=c.lead;$('#quote').textContent=c.quote;$('#interpretation').textContent=c.thought;$('#notes').innerHTML=(i===0?c.notes:detailCopy[i]).map(([h,p],j)=>`<div class="note-item ${j===detailIndex?'selected':''}"><span>0${j+1}</span><div><h3>${h}</h3><p>${p}</p></div></div>`).join('');$('#folio-left').textContent=String(2+i*2).padStart(2,'0');$('#folio-right').textContent=String(3+i*2).padStart(2,'0');$('#page-indicator').textContent=`0${i+1} — 04`;$('#chapter-status').textContent=`${c.title} · 第 ${i+1} 章，共 4 章`;$('#prev').disabled=i===0;$('#next').disabled=i===3;document.querySelectorAll('[data-chapter]').forEach(b=>b.setAttribute('aria-pressed',String(+b.dataset.chapter===i)));}
let turnTime=0;
function changeChapter(i){if(i<0||i>3)return;if(turning){pendingChapter=i;return;}if(i===current)return;const back=i<current;current=i;document.querySelectorAll("[data-chapter]").forEach(b=>b.setAttribute("aria-pressed",String(+b.dataset.chapter===i)));activateScene(i);if(!moving){updateContent(i);setPageTexture(i);render();return;}turning=true;turnTime=performance.now();$('#spread').classList.add(back?'turning-back':'turning');setTimeout(()=>{updateContent(i);setPageTexture(i)},420);setTimeout(()=>{$('#spread').classList.remove('turning','turning-back');turning=false;if(pendingChapter!==null){const next=pendingChapter;pendingChapter=null;changeChapter(next)}},870);wake();}
document.querySelectorAll('[data-chapter]').forEach(b=>b.onclick=()=>changeChapter(+b.dataset.chapter));$('#prev').onclick=()=>changeChapter(current-1);$('#next').onclick=()=>changeChapter(current+1);updateContent(0);
function updateMotion(){document.body.classList.toggle('reduced',!moving);$('#motion').textContent=moving?'暂停动效':'开启动效';$('#motion').setAttribute('aria-pressed',String(!moving));if(!moving){openNow=openTarget;explodeNow=explodeTarget;}wake();}$('#motion').onclick=()=>{moving=!moving;updateMotion()};reduce.addEventListener('change',()=>{moving=!reduce.matches;updateMotion()});
$('#begin').onclick=()=>{openTarget=1;$('#openness').value=100;$('#open-value').value='100%';wake();activateScene(current);$('#scene-action').focus({preventScroll:true});$('.stage').scrollIntoView({behavior:moving?'smooth':'instant',block:'center'});};$('#openness').oninput=e=>{openTarget=+e.target.value/100;$('#open-value').value=e.target.value+'%';if(!moving)openNow=openTarget;wake()};$('#explode').onclick=()=>{explodeTarget=1-explodeTarget;$('#explode').setAttribute('aria-pressed',String(!!explodeTarget));$('#explode').textContent=explodeTarget?'合上镜头':'拆开镜头';if(!moving)explodeNow=explodeTarget;wake()};
function mat(color,roughness=.65,metalness=0){return new T.MeshStandardMaterial({color,roughness,metalness})}
const paper=mat('#eee9dc'),coverMat=mat('#667460'),ink=mat('#343d35'),silver=mat('#b8b9af',.27,.8),black=mat('#242e2b'),copper=mat('#985137',.4,.25),glass=mat('#244c4a',.13,.75);
function box(w,h,d,r,m){const shape=new T.Shape(),x=-w/2,y=-h/2;shape.moveTo(x+r,y);shape.lineTo(x+w-r,y);shape.quadraticCurveTo(x+w,y,x+w,y+r);shape.lineTo(x+w,y+h-r);shape.quadraticCurveTo(x+w,y+h,x+w-r,y+h);shape.lineTo(x+r,y+h);shape.quadraticCurveTo(x,y+h,x,y+h-r);shape.lineTo(x,y+r);shape.quadraticCurveTo(x,y,x+r,y);const g=new T.ExtrudeGeometry(shape,{depth:d,bevelEnabled:true,bevelSegments:2,bevelSize:.015,bevelThickness:.015,steps:1,curveSegments:6});g.translate(0,0,-d/2);const mesh=new T.Mesh(g,m);mesh.castShadow=true;mesh.receiveShadow=true;return mesh;}
function cyl(rad,depth,m){const mesh=new T.Mesh(new T.CylinderGeometry(rad,rad,depth,64),m);mesh.rotation.x=Math.PI/2;mesh.castShadow=true;return mesh}
const pageTextures=[];let leftTexture;
function pageTexture(index,left=false){const c=document.createElement('canvas');c.width=768;c.height=1024;const g=c.getContext('2d');g.fillStyle='#f6f2e6';g.fillRect(0,0,768,1024);g.strokeStyle='#c9c7b8';g.lineWidth=1;g.beginPath();g.moveTo(65,130);g.lineTo(703,130);g.stroke();g.fillStyle='#68715f';g.font='18px sans-serif';g.fillText(left?'CHARLIE / PERSONAL NOTES':`0${index+1} / ${chapters[index].en}`,65,90);g.fillStyle='#374431';g.font='62px Georgia';g.fillText(left?'Charlie.':chapters[index].en.slice(0,6),65,240);g.font='24px serif';g.fillText(left?'个人手记':chapters[index].title,70,302);g.strokeStyle='#88907d';g.lineWidth=2;if(left){for(let j=0;j<3;j++){g.strokeRect(105+j*28,405+j*22,435,280);g.beginPath();g.moveTo(125+j*28,705+j*22);g.lineTo(265+j*28,775+j*22);g.stroke()}g.fillStyle='#974c34';g.fillRect(525,720,28,65)}else{for(let j=0;j<5;j++){g.beginPath();g.moveTo(75,410+j*65);g.lineTo(580-(j%2)*130,410+j*65);g.stroke()}g.beginPath();g.arc(585,650,68,0,Math.PI*2);g.stroke();g.beginPath();g.moveTo(585,590);g.lineTo(585,710);g.moveTo(525,650);g.lineTo(645,650);g.stroke();g.fillStyle='#974c34';g.font='italic 95px Georgia';g.fillText('0'+(index+1),75,890)}g.fillStyle='#69735e';g.font='16px sans-serif';g.fillText(left?'OBSERVE / MAKE / ARRANGE':'FIELD NOTES · OPEN EDITION',65,965);const t=new T.CanvasTexture(c);t.colorSpace=T.SRGBColorSpace;return t;}
function pageFace(texture){const mesh=new T.Mesh(new T.PlaneGeometry(1.97,2.76),new T.MeshBasicMaterial({map:texture,side:T.DoubleSide,toneMapped:false}));mesh.position.set(1.01,0,.20);return mesh}
let rightFace;
function setPageTexture(i){if(rightFace){rightFace.material.map=pageTextures[i];rightFace.material.needsUpdate=true;}wake();}
try{
scene=new T.Scene();camera=new T.PerspectiveCamera(34,1,.1,80);camera.position.set(4.4,6.3,8.3);scene.add(new T.HemisphereLight('#fffcf2','#717b67',1.8));const key=new T.DirectionalLight('#fff6df',2.5);key.position.set(-3,7,5);key.castShadow=true;key.shadow.mapSize.set(2048,2048);key.shadow.camera.left=-7;key.shadow.camera.right=7;key.shadow.camera.top=7;key.shadow.camera.bottom=-7;key.shadow.bias=-.0007;key.shadow.normalBias=.03;scene.add(key);const fill=new T.DirectionalLight('#e5edf3',1.2);fill.position.set(5,3,-5);scene.add(fill);
renderer=new T.WebGLRenderer({canvas:$('#scene'),antialias:true,alpha:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.0;
controls=new OrbitControls(camera,renderer.domElement);controls.target.set(0,.2,0);controls.enableDamping=false;controls.enablePan=false;controls.minDistance=6;controls.maxDistance=17;controls.maxPolarAngle=Math.PI*.47;controls.minPolarAngle=.15;controls.update();controls.saveState();controls.addEventListener('change',()=>{render()});
world=new T.Group();scene.add(world);const floor=new T.Mesh(new T.PlaneGeometry(30,30),new T.ShadowMaterial({opacity:.13}));floor.rotation.x=-Math.PI/2;floor.position.y=-.42;floor.receiveShadow=true;scene.add(floor);
const book=new T.Group();bookModel=book;book.rotation.x=-Math.PI/2;book.rotation.z=-.12;book.position.set(.1,-.14,.2);world.add(book);
const leftCover=box(2.14,2.98,.08,.045,coverMat);leftCover.position.set(-1.055,0,-.13);book.add(leftCover);const leftStack=box(2.02,2.82,.19,.02,paper);leftStack.position.set(-1.03,0,0);book.add(leftStack);
leftTexture=pageTexture(0,true);const lf=pageFace(leftTexture);lf.position.x=-1.03;book.add(lf);
const spine=box(.14,2.98,.24,.025,coverMat);spine.position.z=-.06;book.add(spine);
hinge=new T.Group();book.add(hinge);const rc=box(2.14,2.98,.08,.045,coverMat);rc.position.set(1.055,0,-.13);hinge.add(rc);const rs=box(2.02,2.82,.19,.02,paper);rs.position.set(1.03,0,0);hinge.add(rs);
for(let i=0;i<4;i++)pageTextures.push(pageTexture(i));rightFace=pageFace(pageTextures[0]);hinge.add(rightFace);
for(let i=0;i<13;i++){for(const sign of [-1,1]){const edge=new T.Mesh(new T.BoxGeometry(1.98,.008,.002),mat(i%3?'#cfcbbd':'#f8f4e8'));edge.position.set(sign*1.03,-1.416,-.08+i*.014);(sign===1?hinge:book).add(edge)}}
const ribbon=box(.12,.85,.008,.005,copper);ribbon.position.set(-.3,-1.66,.1);book.add(ribbon);
turnPage=new T.Mesh(new T.PlaneGeometry(1.98,2.76,30,8),new T.MeshStandardMaterial({map:pageTextures[0],side:T.DoubleSide,roughness:.9}));turnPage.geometry.translate(1.0,0,0);turnPage.position.z=.17;turnPage.visible=false;book.add(turnPage);
// Original symbolic camera model: housing, stacked optical rings, controls and removable cap.
cameraModel=new T.Group();cameraModel.position.set(-1.65,.8,-.85);cameraModel.rotation.set(-.12,-.12,-.08);cameraModel.scale.setScalar(.67);world.add(cameraModel);cameraModel.add(box(2.12,1.28,.7,.13,black));const top=box(2.09,.22,.72,.06,silver);top.position.y=.54;cameraModel.add(top);const bottom=box(2.1,.1,.72,.04,silver);bottom.position.y=-.59;cameraModel.add(bottom);const grip=box(.37,.96,.08,.06,ink);grip.position.set(-.8,-.02,.39);cameraModel.add(grip);
const ringParams=[[.58,.18,.41,silver],[.53,.28,.61,black],[.49,.18,.83,silver],[.46,.12,.99,black],[.395,.035,1.065,glass]];ringParams.forEach(([r,d,z,m],i)=>{const o=cyl(r,d,m);o.position.set(.17,-.04,z);cameraModel.add(o);parts.push({o,z,amount:.18+i*.17});});
for(let j=0;j<48;j++){const a=j*Math.PI/24;const tick=box(.014,.09,.018,.003,ink);tick.position.set(.17+Math.cos(a)*.507,-.04+Math.sin(a)*.507,.87);tick.rotation.z=a;cameraModel.add(tick);parts.push({o:tick,z:.87,amount:.52})}
for(let i=0;i<2;i++){const dial=new T.Mesh(new T.CylinderGeometry(i?.1:.19,i?.1:.19,.09,32),silver);dial.position.set(i?.65:-.7,.71,0);cameraModel.add(dial)}const finder=box(.39,.22,.03,.025,glass);finder.position.set(-.56,.34,.375);cameraModel.add(finder);const mark=box(.19,.075,.018,.004,copper);mark.position.set(.7,.36,.375);cameraModel.add(mark);
pen=new T.Group();pen.position.set(2.3,.13,1.05);pen.rotation.set(.12,0,-.83);const shaft=new T.Mesh(new T.CylinderGeometry(.048,.048,2.55,6),copper);pen.add(shaft);const tip=new T.Mesh(new T.ConeGeometry(.048,.22,6),mat('#bf9c6d'));tip.position.y=1.385;pen.add(tip);const graphite=new T.Mesh(new T.ConeGeometry(.019,.08,6),ink);graphite.position.y=1.52;pen.add(graphite);pen.rotation.x=.8;world.add(pen);
const tab=box(.43,.55,.015,.025,copper);tab.position.set(1.5,.03,-1.2);tab.rotation.x=-Math.PI/2;world.add(tab);
$('#loading').hidden=true;function resize(){const rect=$('#viewport').getBoundingClientRect();renderer.setSize(rect.width,rect.height,false);camera.aspect=rect.width/rect.height;camera.updateProjectionMatrix();render()}new ResizeObserver(resize).observe($('#viewport'));resize();
$('#reset').onclick=()=>{controls.reset();world.rotation.y=0;openTarget=.90;$('#openness').value=90;$('#open-value').value='90%';explodeTarget=0;$('#explode').setAttribute('aria-pressed','false');$('#explode').textContent='拆开镜头';if(!moving){openNow=openTarget;explodeNow=0}wake()};$('#rotate').onclick=()=>{world.rotation.y+=Math.PI/6;render()};$('#scene').addEventListener('keydown',e=>{if(['ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();world.rotation.y+=(e.key==='ArrowLeft'?-1:1)*Math.PI/12;render()}});
new IntersectionObserver(es=>{visible=es[0].isIntersecting;if(visible)wake()},{threshold:0}).observe($('#viewport'));document.addEventListener('visibilitychange',()=>{if(!document.hidden)wake()});$('#scene').addEventListener('webglcontextlost',e=>{e.preventDefault();$('#fallback').hidden=false;$('#scene').hidden=true;cancelAnimationFrame(raf)});
}catch(e){console.error(e);$('#loading').hidden=true;$('#fallback').hidden=false;$('#scene').hidden=true;document.querySelectorAll('.stage-controls button,.open-control input').forEach(b=>b.disabled=true)}
function apply(t){if(!hinge)return;applyScene();hinge.rotation.y=-(1-openNow)*Math.PI*.94;parts.forEach(({o,z,amount})=>o.position.z=z+explodeNow*amount);if(turnPage){const phase=(t-turnTime)/850;turnPage.visible=moving&&turning&&phase<1;if(turnPage.visible){turnPage.rotation.y=-Math.PI*phase;const pos=turnPage.geometry.attributes.position;for(let i=0;i<pos.count;i++){const x=pos.getX(i);pos.setZ(i,Math.sin(x/2*Math.PI)*Math.sin(phase*Math.PI)*.3)}pos.needsUpdate=true;turnPage.geometry.computeVertexNormals()}}}
function placeLabels(){if(!sceneReady)return;const rect=$("#viewport").getBoundingClientRect();world.updateMatrixWorld(true);document.querySelectorAll('.hotspot').forEach((el,i)=>{const target=hotspotTargets[i];if(!target){el.hidden=true;return}const v=new T.Vector3();target.getWorldPosition(v);v.project(camera);el.hidden=v.z>1||v.z< -1;const x=(v.x*.5+.5)*rect.width,y=(-v.y*.5+.5)*rect.height;const hx=Math.max(24,Math.min(rect.width-24,x+(current===0?[-30,15,65][i]:0))),hy=Math.max(24,Math.min(rect.height-45,y-36+(current===0?[10,-25,25][i]:0)));el.style.left=hx+"px";el.style.top=hy+"px";const line=document.querySelectorAll("#hotspot-lines path")[i];line.setAttribute("d",`M ${hx} ${hy+16} L ${x} ${y}`);});}
function render(){if(renderer&&scene){apply(performance.now());renderer.render(scene,camera);placeLabels()}}
function wake(){if(!renderer||raf)return;raf=requestAnimationFrame(tick)}
function tick(t){raf=0;if(document.hidden||!visible)return;if(moving){openNow+=(openTarget-openNow)*.085;explodeNow+=(explodeTarget-explodeNow)*.085;}else{openNow=openTarget;explodeNow=explodeTarget}apply(t);renderer.render(scene,camera);placeLabels();if(moving)raf=requestAnimationFrame(tick)}
updateMotion();window.addEventListener('pagehide',()=>{cancelAnimationFrame(raf);controls?.dispose();scene?.traverse(o=>{o.geometry?.dispose();if(o.material){for(const m of [].concat(o.material)){m.map?.dispose();m.dispose()}}});renderer?.dispose()});

// Information is attached to visible model states, rather than an independent decorative loop.
const sceneInfo=[
 {name:'观察 / 镜头里的线索',hint:'点选镜头上的编号，读一条观察线索',steps:['构图','作品','判断'],action:'展开线索 ↗'},
 {name:'制作 / 从内容到呈现',hint:'逐步展开三张工作卡，看看想法怎样变成样本',steps:['内容策划','视觉制作','交互样本'],action:'制作下一步 →'},
 {name:'整理 / 给资料找到位置',hint:'把散开的资料归入作品、素材和方法',steps:['作品','素材','方法'],action:'归入档案 ↗'},
 {name:'偏好 / 让选择直接可见',hint:'调节留白，看标题、解析和主体如何重新分配空间',steps:['留白','解析','字重'],action:'比较另一种排法 ⇄'}
];
const detailCopy=[null,
 [['内容策划','先决定要讲什么、给谁看。你选择过“内容策划 + AI 视觉制作”的展示方向。'],['视觉制作','把内容转成角色、场景与参考图。《时之瓶》的资料卡就是这类实践。'],['交互样本','让画面进入可操作的页面：旋转物件、拆解结构，再根据反馈迭代。']],
 [['作品','电影专题、服装与三维物件网页，按主题集中存放，便于继续修改。'],['素材','角色、场景、参考图与交接资料，和对应创作项目放在一起。'],['方法','把喜欢和不喜欢的部分写成偏好记录、对照案例与设计 Skill。']],
 [['留白','你希望保留适当的空白。拖动滑杆，观察信息是挤在一起，还是彼此有清楚的间隔。'],['解析','保留你喜欢的零件解析：点到这里，卡片上的注释会展开到物件周围。'],['字重','你不喜欢过大过黑的字。点“比较另一种排法”，看同一份内容在字重与空间上的变化。']]
];
function cardTexture(index){const c=document.createElement('canvas');c.width=640;c.height=820;const g=c.getContext('2d');g.fillStyle=index===1?'#e6eadf':'#f8f4e8';g.fillRect(0,0,640,820);g.fillStyle='#46523d';g.font='20px sans-serif';g.fillText('CHARLIE / '+sceneInfo[current].steps[index],45,65);g.strokeStyle='#bcc4af';g.beginPath();g.moveTo(45,90);g.lineTo(590,90);g.stroke();g.fillStyle='#974c34';g.font='italic 60px Georgia';g.fillText('0'+(index+1),45,175);
 if(current===3){const pad=30+tasteValue*65;g.fillStyle='#333c31';g.font=`${tasteValue<.35?'bold ':''}${70-tasteValue*30}px serif`;g.fillText(['留白','解析','字重'][index],pad,250);const size=145+tasteValue*35;g.strokeStyle='#59684c';g.lineWidth=2;g.strokeRect(320-size/2,340,size,150);g.strokeRect(355-size/2,365,size,150);if(detailIndex===1){g.beginPath();g.moveTo(355+size/2,395);g.lineTo(565,320);g.lineTo(600,320);g.stroke();g.font='18px sans-serif';g.fillText('结构',535,300)}for(let j=0;j<3;j++){g.fillStyle='#8a927f';g.fillRect(pad,560+j*(18+tasteValue*22),640-pad*2-(j%2)*70,3)}}
 else {g.fillStyle='#374431';g.font='40px serif';g.fillText(sceneInfo[current].steps[index],45,260);g.strokeStyle='#869478';g.lineWidth=2;if(current===1&&index===1){g.strokeRect(90,320,460,250);g.beginPath();g.arc(260,410,40,0,Math.PI*2);g.moveTo(90,550);g.lineTo(230,430);g.lineTo(360,530);g.lineTo(460,390);g.lineTo(550,490);g.stroke()}else if(current===1&&index===2){g.strokeRect(90,320,460,280);g.strokeRect(125,360,170,200);g.strokeRect(320,360,190,70);g.strokeRect(320,465,190,95)}else{for(let j=0;j<4;j++){g.strokeRect(65,340+j*65,20,20);g.beginPath();g.moveTo(110,350+j*65);g.lineTo(545-j%2*60,350+j*65);g.stroke()}}}g.font='17px sans-serif';g.fillStyle='#67735a';g.fillText('FIELD NOTES / '+chapters[current].en,45,770);const t=new T.CanvasTexture(c);t.colorSpace=T.SRGBColorSpace;return t;}
function refreshCards(){updateTastePreview();sceneCards.forEach((card,i)=>{const face=card.userData.face,old=face.material.map;face.material.map=cardTexture(i);old?.dispose();});}
function selectDetail(i){detailIndex=i;const content=(detailCopy[current]||chapters[current].notes)[i];$('#insight-title').textContent=content[0];$('#insight-copy').textContent=content[1];$('#insight-count').textContent=`0${i+1} / 03`;document.querySelectorAll('[data-detail]').forEach(b=>{b.setAttribute('aria-pressed',String(+b.dataset.detail===i));b.classList.toggle('active',+b.dataset.detail===i)});document.querySelectorAll('.note-item').forEach((el,n)=>el.classList.toggle('selected',n===i));if(current===0){explodeTarget=1;$('#explode').textContent='合上镜头';$('#explode').setAttribute('aria-pressed','true');}if(current===1)buildStep=Math.max(buildStep,i);if(current===3)refreshCards();const body=$('.insight-body');body.classList.remove('changed');void body.offsetWidth;body.classList.add('changed');wake();}
function activateScene(i){if(!sceneReady)return;detailIndex=0;arranged=false;buildStep=0;const info=sceneInfo[i];$('#scene-name').textContent=info.name;$('#scene-instruction').textContent=info.hint;$('#scene-action').textContent=info.action;$('#taste-control').hidden=i!==3;$('#taste-preview').hidden=i!==3;$('#explode').hidden=i!==0;$('#explore-steps').innerHTML=info.steps.map((name,j)=>`<button data-detail="${j}" aria-pressed="${j===0}">${name}</button>`).join('');$('#hotspots').innerHTML=info.steps.map((name,j)=>`<button class="hotspot" data-detail="${j}" aria-label="${name}：查看线索" aria-pressed="${j===0}">0${j+1}</button>`).join('');document.querySelectorAll('[data-detail]').forEach(b=>b.onclick=()=>selectDetail(+b.dataset.detail));hotspotTargets=i===0?[parts[4]?.o,cameraModel,parts[0]?.o]:sceneCards;openTarget=1;$('#openness').value=100;$('#open-value').value='100%';explodeTarget=i===0?1:0;refreshCards();selectDetail(0);wake();}
function applyScene(){if(!sceneReady)return;const f=moving?.085:1;const lerp=(o,target)=>o.position.lerp(new T.Vector3(...target),f);const scale=(o,n)=>o.scale.lerp(new T.Vector3(n,n,n),f);
 lerp(cameraModel,current===0?[-.15,1.15,-.1]:[-2.15,.2,-1.3]);scale(cameraModel,current===0?1.03:.28);lerp(bookModel,current===0?[.1,-.22,.2]:[.1,-.28,.3]);scale(bookModel,current===0?.85:.83);lerp(pen,current===1?[2.15,1,.25]:[2.4,.05,1.1]);
 sceneCards.forEach((card,i)=>{let target,angle;if(current===0){target=[0,-.3,0];scale(card,.001)}else{scale(card,1);if(current===1){target=[(i-1)*1.65,i<=buildStep?.9:.13,(i<=buildStep?-.15:.3)];angle=[-.22,0,(i-1)*-.08];}else if(current===2){target=arranged?[(i-1)*1.5,.5,0]:[[-1.5,1.0,.55],[.1,.15,1],[1.55,.85,-.35]][i];angle=arranged?[-.55,0,0]:[[-.8,.3,-.28],[-1.2,.2,.25],[-.2,-.4,.2]][i];}else{target=[(i-1)*1.55,i===detailIndex?1.08:.4,i===detailIndex?.2:-.25];angle=[-.3,0,(i-1)*-.09];}card.rotation.x+=(angle[0]-card.rotation.x)*f;card.rotation.y+=(angle[1]-card.rotation.y)*f;card.rotation.z+=(angle[2]-card.rotation.z)*f;}lerp(card,target);});}
if(renderer){for(let i=0;i<3;i++){const group=new T.Group();const sheet=box(1.28,1.66,.035,.015,paper);group.add(sheet);const face=new T.Mesh(new T.PlaneGeometry(1.26,1.64),new T.MeshBasicMaterial({map:null,toneMapped:false}));face.position.z=.035;group.add(face);group.userData.face=face;group.scale.setScalar(.001);world.add(group);sceneCards.push(group)}sceneReady=true;activateScene(0);
 // Ray casting selects only visible frontmost semantic objects; drag never triggers selection.
 const ray=new T.Raycaster(),pointer=new T.Vector2();let down=null;$('#scene').addEventListener('pointerdown',e=>down=[e.clientX,e.clientY]);$('#scene').addEventListener('pointerup',e=>{if(!down||Math.hypot(e.clientX-down[0],e.clientY-down[1])>7)return;const r=$('#scene').getBoundingClientRect();pointer.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);ray.setFromCamera(pointer,camera);world.updateMatrixWorld(true);const hits=ray.intersectObjects(current===0?[cameraModel]:sceneCards,true);if(!hits.length)return;let o=hits[0].object;if(current===0){selectDetail(parts.slice(0,5).some(p=>p.o===o)?0:1)}else{while(o.parent!==world&&o.parent)o=o.parent;const n=sceneCards.indexOf(o);if(n>=0)selectDetail(n)}});
}
$('#scene-action').onclick=()=>{if(current===0){selectDetail((detailIndex+1)%3)}else if(current===1){buildStep=(buildStep+1)%3;selectDetail(buildStep);$('#scene-action').textContent=buildStep===2?'重新展开 ↺':'制作下一步 →'}else if(current===2){arranged=!arranged;$('#scene-action').textContent=arranged?'散开资料 ↺':'归入档案 ↗';$('#scene-instruction').textContent=arranged?'作品 / 素材 / 方法：资料回到各自的位置':'把散开的资料归入作品、素材和方法';wake()}else{tasteValue=tasteValue>.4?.1:.8;$('#taste').value=Math.round(tasteValue*100);$('#taste-value').value=Math.round(tasteValue*100)+'%';refreshCards();wake()}};
$('#taste').oninput=e=>{tasteValue=+e.target.value/100;$('#taste-value').value=e.target.value+'%';refreshCards();wake()};

function updateTastePreview(){const layout=$('#taste-layout');if(!layout)return;layout.style.padding=(10+tasteValue*22)+'px';layout.querySelector('h4').style.fontSize=(35-tasteValue*13)+'px';layout.querySelector('h4').style.fontWeight=tasteValue<.35?'800':'400';layout.querySelector('h4').style.marginBottom=(4+tasteValue*20)+'px';layout.querySelector('p').style.marginTop=(5+tasteValue*22)+'px';$('#sample-annotation').hidden=detailIndex!==1;}

if(!renderer){sceneReady=true;activateScene(0);$("#hotspots").hidden=true;$("#hotspot-lines").style.display="none";}
