import * as T from 'three';import{OrbitControls}from './第三方依赖/OrbitControls.js';
const $=id=>document.getElementById(id),info={intake:['01 / INTAKE','进气与整流','入口唇口与中心整流锥引导空气进入核心。这里没有大型旁通风扇，采用轴流涡喷的概念布局。'],compressor:['02 / COMPRESSOR','轴流压气机','多级叶片沿轴向排列。转子和静子交替出现，这里用简化模型展现它们的空间关系。'],combustor:['03 / COMBUSTOR','环形燃烧室','穿孔内衬、燃油分配环与喷注部件围绕中心轴排列。橙色光区只用来表示燃烧位置。'],turbine:['04 / TURBINE','涡轮与轴系','燃气流过涡轮，驱动与它相连的压气机。不同叶片列和共轴转动在这里直观呈现。'],nozzle:['05 / NOZZLE','排气喷口','气流经过尾锥与喷口排出。尾流的亮度、长度经过艺术化处理，便于观察节流输入的变化。']};
let power=.5,mode='cut',paused=matchMedia('(prefers-reduced-motion: reduce)').matches,selected='compressor';
try{const canvas=$('scene'),renderer=new T.WebGLRenderer({canvas,antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.8));renderer.setClearColor(0xe4e1d7);renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.3;renderer.outputColorSpace=T.SRGBColorSpace;
const scene=new T.Scene();scene.fog=new T.Fog(0xe4e1d7,23,55);const camera=new T.PerspectiveCamera(38,1,.1,90);camera.position.set(7,5,12);const controls=new OrbitControls(camera,canvas);controls.target.set(.7,0,0);controls.enableDamping=true;controls.enablePan=false;controls.minDistance=7;controls.maxDistance=24;
scene.add(new T.HemisphereLight(0xdceaff,0x3b4545,3));for(const [c,i,pos]of [[0xffeed6,4,[0,7,5]],[0x6b9dff,5,[-4,2,-5]],[0xff9465,3,[6,3,1]]]){const l=new T.DirectionalLight(c,i);l.position.set(...pos);scene.add(l);}
const floor=new T.Mesh(new T.PlaneGeometry(120,120),new T.MeshStandardMaterial({color:0xe4e1d7,roughness:.9}));floor.rotation.x=-Math.PI/2;floor.position.y=-2;scene.add(floor);const grid=new T.GridHelper(24,32,0xaaa99c,0xd3d0c5);grid.position.y=-1.98;scene.add(grid);
const mats={steel:new T.MeshStandardMaterial({color:0x98abb7,metalness:.8,roughness:.26}),dark:new T.MeshStandardMaterial({color:0x34424b,metalness:.75,roughness:.38}),gold:new T.MeshStandardMaterial({color:0xcda46a,metalness:.72,roughness:.3}),blue:new T.MeshStandardMaterial({color:0x70856f,metalness:.55,roughness:.28}),hot:new T.MeshStandardMaterial({color:0xc26a43,metalness:.6,roughness:.32})};
const groups={},pick=[],shells=[],rotors=[];Object.keys(info).forEach((id,i)=>{const g=new T.Group();g.userData.part=id;g.userData.offset=(i-2)*.9;groups[id]=g;scene.add(g);});
function add(geo,mat,parent,x=0,y=0,z=0){const o=new T.Mesh(geo,mat);o.position.set(x,y,z);parent.add(o);let p=parent;while(p&&!p.userData.part)p=p.parent;o.userData.part=p?.userData.part;pick.push(o);return o;}
function cyl(r1,r2,len,parent,x,mat=mats.steel,open=false,start=0,angle=Math.PI*2){const o=add(new T.CylinderGeometry(r1,r2,len,64,1,open,start,angle),mat,parent,x);o.rotation.z=-Math.PI/2;return o;}
function ring(radius,tube,parent,x,mat=mats.steel){const o=add(new T.TorusGeometry(radius,tube,8,64),mat,parent,x);o.rotation.y=Math.PI/2;return o;}
function shell(radius,len,parent,x,mat=mats.dark){for(let i=0;i<2;i++){const o=cyl(radius,radius,len,parent,x,mat,true,i*Math.PI,Math.PI);o.material=mat.clone();o.material.side=T.DoubleSide;if(i===0)shells.push(o);}}
function bolts(parent,x,r,n=16){const geo=new T.CylinderGeometry(.038,.038,.065,6);for(let i=0;i<n;i++){const a=i/n*Math.PI*2;const b=add(geo,mats.steel,parent,x,Math.cos(a)*r,Math.sin(a)*r);b.rotation.z=Math.PI/2;}}
function bladeRow(parent,x,r,n,rotating,material){const row=new T.Group();parent.add(row);row.position.x=x;const hub=.25,span=r-hub;const geo=new T.BoxGeometry(.16,span,.045,3,7,1);const p=geo.attributes.position;for(let i=0;i<p.count;i++){const t=(p.getY(i)+span/2)/span;const xx=p.getX(i),zz=p.getZ(i);const a=.15+t*.6;p.setXYZ(i,xx*Math.cos(a)-zz*Math.sin(a)+t*t*.1,p.getY(i),xx*Math.sin(a)+zz*Math.cos(a));}geo.computeVertexNormals();for(let i=0;i<n;i++){const g=new T.Group();g.rotation.x=i/n*Math.PI*2;row.add(g);add(geo,material,g,0,hub+span/2,0);}cyl(.29,.29,.15,row,0,mats.dark);if(rotating)rotors.push(row);}
// Intake lip, bellmouth, nose cone and struts.
ring(1.04,.09,groups.intake,-3.25);shell(1.03,.48,groups.intake,-3.03,mats.steel);cyl(.24,0,.7,groups.intake,-3.13,mats.steel);for(let i=0;i<4;i++){const a=i*Math.PI/2;const s=add(new T.BoxGeometry(.12,.76,.065),mats.dark,groups.intake,-2.75,Math.cos(a)*.61,Math.sin(a)*.61);s.rotation.x=a;}
// Six compressor rotor rows and five stator rows with separate tip rings.
for(let i=0;i<6;i++){const x=-2.5+i*.39,r=.97-i*.055;bladeRow(groups.compressor,x,r,24+i*2,true,i%2?mats.steel:mats.blue);ring(r+.035,.032,groups.compressor,x);if(i<5)bladeRow(groups.compressor,x+.195,r-.02,22,false,mats.gold);}
shell(1.03,2.5,groups.compressor,-1.48);for(const x of [-2.68,-.25]){ring(1.07,.065,groups.compressor,x,mats.blue);bolts(groups.compressor,x,1.07);}cyl(.14,.14,5.6,groups.compressor,-.2,mats.steel);
// Annular liner, injector ring and perforation-like collars.
shell(1.04,1.55,groups.combustor,.61);shell(.78,1.34,groups.combustor,.61,mats.gold);cyl(.33,.33,1.4,groups.combustor,.61,mats.dark,true);ring(.64,.045,groups.combustor,-.02,mats.hot);
for(let i=0;i<16;i++){const a=i/16*Math.PI*2;const injector=add(new T.CylinderGeometry(.045,.06,.23,12),mats.gold,groups.combustor,.06,Math.cos(a)*.65,Math.sin(a)*.65);injector.rotation.z=Math.PI/2;for(let j=0;j<5;j++){const hole=add(new T.TorusGeometry(.038,.012,6,12),mats.dark,groups.combustor,.2+j*.22,Math.cos(a)*.785,Math.sin(a)*.785);hole.lookAt(hole.position.clone().add(new T.Vector3(0,Math.cos(a),Math.sin(a))));}}
const glowMaterial=new T.MeshBasicMaterial({color:0xff7733,transparent:true,opacity:.15,side:T.DoubleSide,depthWrite:false,blending:T.AdditiveBlending});const glow=cyl(.68,.68,1.2,groups.combustor,.65,glowMaterial,true);
// Two turbine rotor stages and stationary guide vanes.
for(let i=0;i<2;i++){bladeRow(groups.turbine,1.56+i*.36,.78,30,true,mats.hot);bladeRow(groups.turbine,1.4+i*.36,.81,26,false,mats.gold);ring(.88,.045,groups.turbine,1.56+i*.36);}shell(.92,.85,groups.turbine,1.7,mats.steel);bolts(groups.turbine,2.12,.92);
// Convergent nozzle, tail cone and petal seams.
cyl(.53,.91,1.05,groups.nozzle,2.68,mats.dark,true);cyl(0,.30,.88,groups.nozzle,2.60,mats.gold);ring(.54,.035,groups.nozzle,3.21);for(let i=0;i<20;i++){const a=i/20*Math.PI*2;const pts=[new T.Vector3(2.16,Math.cos(a)*.91,Math.sin(a)*.91),new T.Vector3(3.20,Math.cos(a)*.54,Math.sin(a)*.54)];add(new T.TubeGeometry(new T.CatmullRomCurve3(pts),1,.016,5,false),mats.steel,groups.nozzle);}
// Exhibition cradle.
for(const x of [-1.9,1.1]){const post=new T.Mesh(new T.BoxGeometry(.24,.68,.28),mats.dark);post.position.set(x,-1.58,0);scene.add(post);const foot=new T.Mesh(new T.BoxGeometry(.7,.12,1.65),mats.dark);foot.position.set(x,-1.9,0);scene.add(foot);}
// Stylised translucent exhaust; no afterburner or shock-diamond claim.
const flameMat=new T.ShaderMaterial({transparent:true,depthWrite:false,side:T.DoubleSide,blending:T.AdditiveBlending,uniforms:{time:{value:0},power:{value:.5}},vertexShader:`varying vec2 vUv;void main(){vUv=uv;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}`,fragmentShader:`varying vec2 vUv;uniform float time;uniform float power;void main(){float t=vUv.y;float wave=.65+.35*sin(t*38.-time*13.+sin(vUv.x*37.+time*4.));float fade=pow(1.-t,1.5);vec3 c=mix(vec3(.12,.34,1.),vec3(.9,.32,.06),t*.6);float a=fade*(.10+power*.30)*wave;gl_FragColor=vec4(c*1.7,a);}`});
const flame=new T.Mesh(new T.CylinderGeometry(.035,.49,1,48,32,true),flameMat);flame.rotation.z=-Math.PI/2;groups.nozzle.add(flame);
const count=480,arr=new Float32Array(count*3),seeds=Array.from({length:count},()=>[Math.random(),Math.random()*6.283,Math.random()]);const pg=new T.BufferGeometry();pg.setAttribute('position',new T.BufferAttribute(arr,3));const sparks=new T.Points(pg,new T.PointsMaterial({color:0x719dff,size:.028,transparent:true,opacity:.4,depthWrite:false,blending:T.AdditiveBlending}));groups.nozzle.add(sparks);
function detail(id){selected=id;const d=info[id];$('part-no').textContent=d[0];$('part-name').textContent=d[1];$('part-copy').textContent=d[2];document.querySelectorAll('[data-part]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.part===id)));}
function setMode(m){mode=m;document.querySelectorAll('[data-mode]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.mode===m)));shells.forEach(o=>o.visible=m==='solid');}
document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>setMode(b.dataset.mode));document.querySelectorAll('[data-part]').forEach(b=>b.onclick=()=>{detail(b.dataset.part);if(mode==='solid'&&selected!=='intake'&&selected!=='nozzle')setMode('cut');});
function throttle(v){power=v/100;$('throttle').value=v;$('value').textContent=v+'%';const label=v<30?'慢车':v<75?'巡航':'高推力';$('state-tag').textContent=label+' · 示意';$('state-copy').textContent=v===0?'零节流演示：转子保持低速，尾流亮度降低；不等同于关机。':label+'状态：尾流与转动强度随输入变化，数值不对应真实推力。';document.querySelectorAll('[data-power]').forEach(b=>b.setAttribute('aria-pressed',String(+b.dataset.power===v)));}
$('throttle').oninput=e=>throttle(+e.target.value);document.querySelectorAll('[data-power]').forEach(b=>b.onclick=()=>throttle(+b.dataset.power));function pauseLabel(){$('pause').innerHTML=paused?'继续动画 <span>↗</span>':'暂停动画 <span>Ⅱ</span>';$('pause').setAttribute('aria-pressed',String(paused));}$('pause').onclick=()=>{paused=!paused;pauseLabel();};pauseLabel();window.addEventListener('study-motion',e=>{paused=e.detail;pauseLabel();});const reduced=matchMedia('(prefers-reduced-motion: reduce)');reduced.addEventListener('change',e=>{if(e.matches){paused=true;pauseLabel();}});
function view(v){camera.position.set(...({side:[.4,3,14],intake:[-13,2,2],rear:[13,2,2],reset:[7,5,12]}[v]));controls.target.set(.7,0,0);controls.update();}document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>view(b.dataset.view));$('reset').onclick=()=>view('reset');canvas.onkeydown=e=>{if(['ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();camera.position.sub(controls.target).applyAxisAngle(new T.Vector3(0,1,0),e.key==='ArrowLeft'?-.15:.15).add(controls.target);controls.update();}};
const ray=new T.Raycaster();let down;canvas.addEventListener('pointerdown',e=>down=[e.clientX,e.clientY]);canvas.addEventListener('pointerup',e=>{if(!down||Math.hypot(e.clientX-down[0],e.clientY-down[1])>5)return;const r=canvas.getBoundingClientRect();ray.setFromCamera(new T.Vector2((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1),camera);const hit=ray.intersectObjects(pick).find(h=>h.object.visible&&h.object.userData.part);if(hit)detail(hit.object.userData.part);});
function resize(){renderer.setSize(canvas.clientWidth,canvas.clientHeight,false);camera.aspect=canvas.clientWidth/canvas.clientHeight;camera.updateProjectionMatrix();}new ResizeObserver(resize).observe(canvas);resize();setMode('cut');throttle(50);$('loading').hidden=true;let last=performance.now(),time=0;function frame(now){requestAnimationFrame(frame);const dt=Math.min((now-last)/1000,.05);last=now;if(!paused){time+=dt;rotors.forEach(r=>r.rotation.x+=dt*(.4+power*3.5));}Object.values(groups).forEach(g=>{const target=mode==='explode'?g.userData.offset:0;g.position.x+= (target-g.position.x)*(reduced.matches?1:Math.min(dt*7,1));});const len=.55+power*3.2;flame.scale.y=len;flame.position.x=3.23+len/2;flameMat.uniforms.time.value=time;flameMat.uniforms.power.value=power;glowMaterial.opacity=.08+power*.22;for(let i=0;i<count;i++){const [s,a,r]=seeds[i],t=(s+time*(.3+power*.6))%1;arr[i*3]=3.22+t*len;arr[i*3+1]=Math.cos(a)*r*.44*(1-t*.7);arr[i*3+2]=Math.sin(a)*r*.44*(1-t*.7);}pg.attributes.position.needsUpdate=true;sparks.material.opacity=.12+power*.4;controls.update();renderer.render(scene,camera);}requestAnimationFrame(frame);canvas.addEventListener('webglcontextlost',e=>{e.preventDefault();$('loading').hidden=false;$('loading').textContent='三维显示已中断，请刷新恢复。';});
}catch(e){$('loading').hidden=false;$('loading').textContent='当前浏览器无法显示三维模型，请使用支持 WebGL 的浏览器。';document.querySelectorAll('button,input').forEach(b=>b.disabled=true);console.error(e);}
