const root=document.documentElement,reduce=matchMedia('(prefers-reduced-motion: reduce)'),motion=document.getElementById('motion-all'),tour=document.getElementById('tour'),status=document.getElementById('tour-status');let off=reduce.matches,timer=null,step=0;
root.classList.add('motion-ready');const observer=new IntersectionObserver(items=>items.forEach(i=>{if(i.isIntersecting){i.target.classList.add('is-visible');observer.unobserve(i.target);}}),{threshold:.08});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));
function stopTour(message='导览已停止，可以自由观察。'){clearTimeout(timer);timer=null;tour.setAttribute('aria-pressed','false');tour.innerHTML='播放拆解导览 <span>▷</span>';status.textContent=message;}
function setMotion(){root.classList.toggle('motion-off',off);motion.setAttribute('aria-pressed',String(off));motion.textContent=off?'恢复动效 ↗':'减少动效 Ⅱ';window.dispatchEvent(new CustomEvent('study-motion',{detail:off}));if(off)stopTour('已减少动态效果，可手动选择部件。');}motion.onclick=()=>{off=!off;setMotion();};reduce.addEventListener('change',e=>{off=e.matches;setMotion();});setMotion();
let pending=false;function updateProgress(){pending=false;const max=root.scrollHeight-innerHeight;document.querySelector('.reading-progress').style.transform=`scaleX(${max>0?scrollY/max:0})`;}addEventListener('scroll',()=>{if(!pending){pending=true;requestAnimationFrame(updateProgress);}},{passive:true});updateProgress();
const steps=[['intake','进气口 / 先观察入口与整流锥。'],['compressor','压气机 / 比较交替排列的转子与静子。'],['combustor','燃烧室 / 找到围绕中心轴的环形结构。'],['turbine','涡轮 / 沿轴线观察后段叶片。'],['nozzle','喷口 / 空气路径在这里结束。']];
function next(){if(step>=steps.length){stopTour('导览完成。现在可以选择任意部件继续观察。');return;}const [id,text]=steps[step++];document.querySelector(`[data-part="${id}"]`).click();status.textContent=text;timer=setTimeout(next,3800);}
tour.onclick=()=>{if(tour.getAttribute('aria-pressed')==='true'){stopTour();return;}if(off){status.textContent='当前已减少动效，请恢复动效后播放自动导览。';return;}document.querySelector('[data-mode="explode"]').click();document.querySelector('[data-view="side"]').click();tour.setAttribute('aria-pressed','true');tour.innerHTML='停止导览 <span>Ⅱ</span>';step=0;next();};
document.querySelectorAll('.jump').forEach(b=>b.onclick=()=>{stopTour('已切换到所选观察方式。');const action=b.dataset.jump;if(action==='power')document.querySelector('[data-power="100"]').click();else document.querySelector(`[data-mode="${action}"]`).click();document.getElementById('workbench').scrollIntoView({behavior:off?'instant':'smooth',block:'start'});});
document.querySelectorAll('aside button,aside input,.orientation button,#scene').forEach(el=>el.addEventListener('pointerdown',()=>{if(timer)stopTour();}));
new MutationObserver(()=>{const p=document.querySelector('.part-info');p.classList.remove('updated');requestAnimationFrame(()=>p.classList.add('updated'));}).observe(document.getElementById('part-name'),{childList:true});
document.addEventListener('visibilitychange',()=>{if(document.hidden&&timer)stopTour('导览已暂停，可回来后重新播放。');});
