const studies=[
 {en:'THE COLOUR STUDIO',title:'色彩的<br>实验场。',copy:'钴蓝背景与朱红色面交叠。清晰的边界进入球体，变成弯曲、压缩的色带。',light:'方向明确的棚灯',focus:'色块边界与高光形状',mood:'鲜明 / 理性 / 人工',location:'STUDIO / 摄影棚',position:'0% 0%',palette:['#234be6','#ee563b','#f0e9d8'],alt:'蓝色摄影棚中透明水晶球的概念影像'},
 {en:'THE OPEN DESERT',title:'把日落，<br>收进球里。',copy:'暖橙色的沙地延伸到远处。低角度的光照亮球体边缘，地平线在透明的曲面里弯折。',light:'低角度的暖色光',focus:'地平线与球体轮廓',mood:'开阔 / 温暖 / 安静',location:'DESERT / 旷野',position:'100% 0%',palette:['#e77935','#eab880','#785649'],alt:'暖色沙漠环境中透明水晶球的概念影像'},
 {en:'UNDER THE CANOPY',title:'绿色，<br>有了层次。',copy:'树冠筛下零散的光，苔藓带来柔软的底色。球体收纳叶片与暗部，也把光斑聚在表面。',light:'树叶间的斑驳光',focus:'明暗交界与绿色反射',mood:'湿润 / 柔和 / 自然',location:'FOREST / 森林',position:'0% 100%',palette:['#214c39','#859b49','#c7d39c'],alt:'苔藓森林中透明水晶球的概念影像'},
 {en:'AFTER DARK',title:'夜色里，<br>光有形状。',copy:'紫色、青色与洋红来自不同方向。点状和条状光源，在球面上留下交错的城市片段。',light:'多方向的彩色灯光',focus:'光带叠加与明亮反射',mood:'冷冽 / 浓郁 / 都市',location:'NIGHT CITY / 夜城',position:'100% 100%',palette:['#382978','#39bed0','#dd4e9a'],alt:'紫色夜城霓虹环境中透明水晶球的概念影像'}
];
const $=id=>document.getElementById(id),buttons=[...document.querySelectorAll('button[data-env]')];
function selectEnvironment(index){const s=studies[index];if(!s)return;buttons.forEach((b,i)=>b.setAttribute('aria-pressed',String(i===index)));$('art').style.backgroundPosition=index===1?'83.333% -16.666%':s.position;$('art').style.backgroundSize=index===1?'250% 250%':'200% 200%';$('art').setAttribute('aria-label',s.alt);$('stage').dataset.env=index;$('stage-index').textContent=String(index+1).padStart(2,'0');$('note-number').textContent=String(index+1).padStart(3,'0');$('env-en').textContent=s.en;$('env-title').innerHTML=s.title;$('env-copy').textContent=s.copy;$('light-note').textContent=s.light;$('focus-note').textContent=s.focus;$('mood-note').textContent=s.mood;$('stage-location').textContent=s.location;document.querySelectorAll('.swatches i').forEach((el,i)=>el.style.setProperty('--swatch',s.palette[i]));}
buttons.forEach((b,i)=>{b.addEventListener('click',()=>selectEnvironment(i));b.addEventListener('keydown',e=>{if(!['ArrowRight','ArrowLeft','Home','End'].includes(e.key))return;e.preventDefault();const next=e.key==='Home'?0:e.key==='End'?3:(i+(e.key==='ArrowRight'?1:3))%4;buttons[next].focus();selectEnvironment(next);});});
$('exposure').addEventListener('input',e=>{$('art').style.setProperty('--exposure',e.target.value/100);$('exposure-value').textContent=e.target.value+'%';});
const reduced=matchMedia('(prefers-reduced-motion: reduce)');function motionOff(){$('stage').classList.remove('moving');$('motion').setAttribute('aria-pressed','false');$('motion').textContent=reduced.matches?'已遵循减少动态效果':'开启微动 ↗';$('motion').disabled=reduced.matches;}motionOff();reduced.addEventListener('change',motionOff);$('motion').addEventListener('click',()=>{const active=$('stage').classList.toggle('moving');$('motion').setAttribute('aria-pressed',String(active));$('motion').textContent=active?'暂停微动 Ⅱ':'开启微动 ↗';});
const image=new Image();image.onerror=()=>{$('asset-error').hidden=false;};image.src='素材/四种环境.png';
